### ISSUE TITLE
How to run this app?

### ISSUE THREAD

**Issue by TarunKumarUpadhyay** [turnly/turnly#90]
How do i install/run this app?
Any docs to have this thing installed would be really appreciated.

**Comment by efraa** [comment]
Hello @TarunKumarUpadhyay, thanks for reaching us.

We are working on an `ops` with `docker-compose` to facilitate the deployment of the project in development mode but it is not ready yet, we will notify you when it is available.

**Comment by FredoPro** [comment]
Is it finished already?

**Comment by efraa** [comment]
We'll be closing this issue in favor of using discussions for topics like this.

Check: https://github.com/turnly/turnly/discussions/89
