### ISSUE TITLE
¿Cómo puedo levantar el proyecto?

### ISSUE THREAD

**Issue by intelnexoec** [turnly/turnly#94]

**Comment by efraa** [comment]
Hola @intelnexoec, gracias por contactarnos.

Estamos trabajando en un `ops` con `docker-compose` para facilitar la implementación del proyecto en modo desarrollo pero aún no está listo, les informaremos cuando esté disponible.

**Comment by intelnexoec** [comment]
Muchas gracias amigo

**Comment by efraa** [comment]
We'll be closing this issue in favor of using discussions for topics like this.

Check: https://github.com/turnly/turnly/discussions/89
